# .github/workflows/publish.yml
name: Publish @ocbwoy3/libocbwoy3

on:
    push:
        paths:
            - "packages/libocbwoy3/**"
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun install

            - name: Build lib
              run: |
                  cd packages/libocbwoy3
                  bun run build

            - name: Publish to GitHub Packages
              run: |
                  cd packages/libocbwoy3
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
